Repository ingresso-group/pyticketswitch, pull requests merged in 2018-11, with the labels that each got.

#84 Add agent_reference to purchase call, update dependencies
  CHANGELOG.md
  docs/conf.py
  pyticketswitch/__init__.py
  pyticketswitch/client.py
  pyticketswitch/payment_methods.py
  pyticketswitch/status.py
  requirements/common.txt
  setup.py
  tests/test_client.py
Labels: bug, enhancement, missing functionality

#80 Correct some typos in docs
  pyticketswitch/client.py
Labels: docs

#82 Fix results_remaining not being a PaginationMixin constructor argument
  CHANGELOG.md
  pyticketswitch/mixins.py
  tests/test_mixins.py
Labels: missing functionality

#86 Fix valid "quanities" and add cached_number_available
  CHANGELOG.md
  docs/conf.py
  features/list-performances.feature
  pyticketswitch/__init__.py
  pyticketswitch/availability.py
  setup.py
  tests/test_availability.py
Labels: missing functionality
